### PR TITLE
Fix #296: Figure out threads and ensure UI is updated correctly

### LINKED ISSUE #296: Threading issue with noLocationButRequesting calling updateUI
```
Exception android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
  at android.view.ViewRootImpl.checkThread (ViewRootImpl.java:9243)
  at android.view.ViewRootImpl.requestLayout (ViewRootImpl.java:1622)
  at android.view.View.requestLayout (View.java:24871)
  at android.view.View.requestLayout (View.java:24871)
  at android.view.View.requestLayout (View.java:24871)
  at android.view.View.requestLayout (View.java:24871)
  at android.view.View.requestLayout (View.java:24871)
  at android.view.View.requestLayout (View.java:24871)
  at androidx.constraintlayout.widget.ConstraintLayout.requestLayout (ConstraintLayout.java:3605)
  at android.view.View.requestLayout (View.java:24871)
  at android.view.View.requestLayout (View.java:24871)
  at androidx.constraintlayout.widget.ConstraintLayout.requestLayout (ConstraintLayout.java:3605)
  at android.view.View.requestLayout (View.java:24871)
  at android.widget.TextView.checkForRelayout (TextView.java:10123)
  at android.widget.TextView.setText (TextView.java:6398)
  at android.widget.TextView.setText (TextView.java:6201)
  at android.widget.TextView.setText (TextView.java:6158)
  at android.widget.TextView.setText (TextView.java:6502)
  at net.twisterrob.sun.android.SunAngleWidgetConfiguration.updateUI (SunAngleWidgetConfiguration.java:504)
  at net.twisterrob.sun.android.SunAngleWidgetConfiguration.update (SunAngleWidgetConfiguration.java:565)
  at net.twisterrob.sun.android.SunAngleWidgetConfiguration$7.accept (SunAngleWidgetConfiguration.java:211)
  at net.twisterrob.sun.android.SunAngleWidgetConfiguration$7.accept (SunAngleWidgetConfiguration.java:209)
  at net.twisterrob.sun.android.SunAngleWidgetConfiguration$LocationUpdater.invoke (SunAngleWidgetConfiguration.java:647)
  at net.twisterrob.sun.android.SunAngleWidgetConfiguration$LocationUpdater.invoke (SunAngleWidgetConfiguration.java:620)
  at net.twisterrob.sun.android.LocationRetriever$get$1$noLocationButRequesting$1.invoke (LocationRetriever.kt:54)
  at net.twisterrob.sun.android.LocationRetriever$get$1$noLocationButRequesting$1.invoke (LocationRetriever.kt:50)
  at kotlin.concurrent.ThreadsKt$thread$thread$1.run (Thread.kt:30)
```

image

### PR DESCRIPTION
**Pull request by TWiStErRob**

### CODE REVIEW

File: feature/configuration/src/main/java/net/twisterrob/sun/android/SunAngleWidgetConfiguration.java [hunk 1]
```diff
@@ -556,7 +515,16 @@ void updateUI(@NonNull SunSearchResults results) {
 		return sun;
 	}
 
+	@AnyThread
 	protected void update(@Nullable Location loc) {
+		SunSearchResults results = calculateResults(loc);
+		new Handler(Looper.getMainLooper()).post(() -> {
+			updateUI(results);
+			lastResults = results;
+		});
```
Comment (TWiStErRob) [inline feature/configuration/src/main/java/net/twisterrob/sun/android/SunAngleWidgetConfiguration.java:524]: fix
